# Generated by Django 5.0 on 2023-12-20 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                ("AboutId", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(default="Name", max_length=200)),
                ("Profession", models.CharField(default="Name", max_length=200)),
                (
                    "ProfileImage",
                    models.ImageField(default="Profile", upload_to="profile"),
                ),
                ("Fb", models.CharField(default="Name", max_length=200)),
                ("Twitter", models.CharField(default="Name", max_length=200)),
                ("Instgram", models.CharField(default="Name", max_length=200)),
                ("Linkedlist", models.CharField(default="Linkdin", max_length=200)),
                (
                    "Description",
                    models.TextField(default="Description", max_length=3000),
                ),
                ("Dob", models.CharField(default="Dob", max_length=200)),
                ("Email", models.CharField(default="Email", max_length=200)),
                ("Contact", models.CharField(default="Contact", max_length=200)),
                ("Address", models.CharField(default="Address", max_length=200)),
                ("GoogleMap", models.TextField(default="Description", max_length=4000)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                ("ContactId", models.AutoField(primary_key=True, serialize=False)),
                ("ContactName", models.CharField(default="Name", max_length=100)),
                ("ContactEmail", models.CharField(default="Name", max_length=100)),
                ("ContactMsg", models.TextField(default="Message", max_length=3000)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("MarkTime", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Cv",
            fields=[
                ("Cvid", models.AutoField(primary_key=True, serialize=False)),
                ("Cvfile", models.FileField(default="cv.pdf", upload_to="cv")),
                ("Hirelink", models.CharField(default="Hire link", max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("ReviewId", models.AutoField(primary_key=True, serialize=False)),
                ("ClientName", models.CharField(max_length=250)),
                ("clientReview", models.TextField(max_length=2000)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceModel",
            fields=[
                ("ServiceId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ServiceTitle",
                    models.CharField(default="Service Title", max_length=200),
                ),
                (
                    "ServiceDesc",
                    models.CharField(default="Description", max_length=200),
                ),
                (
                    "ServiceIcon",
                    models.CharField(default="Service Icon Class", max_length=200),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SettingModel",
            fields=[
                ("SiteId", models.AutoField(primary_key=True, serialize=False)),
                ("SiteTitle", models.CharField(default="Site Title", max_length=200)),
                ("SiteLogo", models.ImageField(default="work.jpg", upload_to="site/")),
                (
                    "SiteFavicon",
                    models.ImageField(default="work.jpg", upload_to="site/"),
                ),
                (
                    "SiteDesc",
                    models.TextField(default="Site Description", max_length=200),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkillModel",
            fields=[
                ("SkillId", models.AutoField(primary_key=True, serialize=False)),
                ("SkillTitle", models.CharField(default="SKill Title", max_length=200)),
                (
                    "SkillPosition",
                    models.CharField(default=" Position ", max_length=200),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkModel",
            fields=[
                ("Workid", models.AutoField(primary_key=True, serialize=False)),
                ("WorkTitle", models.CharField(default="Work Title", max_length=200)),
                ("WorkLink", models.CharField(default="Service Title", max_length=200)),
                ("client", models.CharField(default="", max_length=200)),
                ("languages", models.TextField(default="", max_length=1055)),
                (
                    "WorkThumbnail",
                    models.ImageField(default="work.jpg", upload_to="works"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "Serviceid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.servicemodel",
                    ),
                ),
            ],
        ),
    ]
