import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import * as fa from 'react-icons/fa';
import MainNavbar from '@/components/MainNavbar';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <body className="bg-[url(/images/bg.jpg)] bg-no-repeat bg-cover  text-white">
        <section className="bg-homeTwoBg-dark min-h-screen bg-no-repeat bg-center bg-cover bg-fixed md:pb-[14%] w-full">
               <div className="container w-full bg-black lg:bg-transparent lg:dark:bg-transparent flex justify-between py-5 lg:px-0 lg:pt-[50px]">
  <div className="w-full flex justify-between px-4">
    <a href="/">
      <Image
      alt="logo"
      src="/images/logo.png"
      width={153}
      height={26}
      className="h-[26px] lg:h-[32px]"
      />
    </a>
  </div>
</div>
<div className="container grid grid-cols-12 md:gap-10 justify-between lg:mt-[220px]">
  <div className="col-span-12 lg:col-span-4 hidden lg:block h-screen sticky top-44 scrollbar scrollbar-thumb-gray-900 scrollbar-track-gray-100">
    <div className="w-full mb-6 lg:mb-0 mx-auto relative  text-center bg-black px-6 rounded-[20px] mt-[180px] md:mt-[220px] lg:mt-0">
      <Image
        alt="avatar"
        src="/images/about.jpg"
        width={240}
        height={240}
        className="w-[240px] absolute left-[50%] transform -translate-x-[50%] h-[240px] drop-shadow-xl mx-auto rounded-[20px] -mt-[140px]"
        loading="lazy"
      />
      <div className="pt-[100px] pb-8">
        <h1 className="mt-6 mb-1 text-5xl font-semibold text-white py-2">
          Monalisa Ashley
        </h1>
        <h3 className="mb-4  inline-block bg-[#1D1D1D] px-5 py-2 rounded-lg text-[#A6A6A6]">
          Ui/Ux Designer
        </h3>
        <div className="flex justify-center space-x-3">
          <a
            href="https://www.facebook.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <span className="socialbtn text-[#1773EA]">
             <fa.FaFacebook size={"24px"}/>
            </span>
          </a>
          <a
            href="https://twitter.com/"
           
          >
            <span className="socialbtn text-[#1C9CEA]">
              <fa.FaTwitter size={"24px"} />
            </span>
          </a>
          <a
            href="https://dribbble.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            
            <span className="socialbtn text-[#e14a84]">
            <fa.FaDribbble size={"24px"} />
            </span>
          </a>
          <a
            href="https://www.linkedin.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <span className="socialbtn text-info">
            <fa.FaLinkedinIn size={"24px"} />
            </span>
          </a>
        </div>
        <div className="p-7 rounded-2xl mt-7 bg-[#1D1D1D]">
          <div className="flex py-2.5 border-b border-[#3D3A3A]">
            <span className="flex-shrink-0 socialbtn bg-black text-secondary shadow-md">
              <svg
                stroke="currentColor"
                fill="currentColor"
                strokeWidth={0}
                viewBox="0 0 320 512"
                height="1em"
                width="1em"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M272 0H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h224c26.5 0 48-21.5 48-48V48c0-26.5-21.5-48-48-48zM160 480c-17.7 0-32-14.3-32-32s14.3-32 32-32 32 14.3 32 32-14.3 32-32 32zm112-108c0 6.6-5.4 12-12 12H60c-6.6 0-12-5.4-12-12V60c0-6.6 5.4-12 12-12h200c6.6 0 12 5.4 12 12v312z" />
              </svg>
            </span>
            <div className="text-left ml-2.5">
              <p className="text-xs text-[#A6A6A6]">
                Phone
              </p>
              <p className="text-white break-all">
                <a
                  className="hover:text-primary duration-300 transition"
                  href="tel:+1234567890"
                >
                  +123 456 7890
                </a>
              </p>
            </div>
          </div>
          <div className="flex py-2.5 border-b border-[#3D3A3A]">
            <span className="flex-shrink-0 socialbtn bg-black text-[#6AB5B9] shadow-md">
              <svg
                stroke="currentColor"
                fill="currentColor"
                strokeWidth={0}
                viewBox="0 0 384 512"
                height="1em"
                width="1em"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M172.268 501.67C26.97 291.031 0 269.413 0 192 0 85.961 85.961 0 192 0s192 85.961 192 192c0 77.413-26.97 99.031-172.268 309.67-9.535 13.774-29.93 13.773-39.464 0zM192 272c44.183 0 80-35.817 80-80s-35.817-80-80-80-80 35.817-80 80 35.817 80 80 80z" />
              </svg>
            </span>
            <div className="text-left ml-2.5">
              <p className="text-xs text-[#A6A6A6]">
                Location
              </p>
              <p className="text-white break-all">Hong kong china</p>
            </div>
          </div>
          <div className="flex py-2.5 border-b border-[#3D3A3A]">
            <span className="flex-shrink-0 socialbtn bg-black text-primary shadow-md">
              <svg
                stroke="currentColor"
                fill="currentColor"
                strokeWidth={0}
                viewBox="0 0 512 512"
                height="1em"
                width="1em"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M176 216h160c8.84 0 16-7.16 16-16v-16c0-8.84-7.16-16-16-16H176c-8.84 0-16 7.16-16 16v16c0 8.84 7.16 16 16 16zm-16 80c0 8.84 7.16 16 16 16h160c8.84 0 16-7.16 16-16v-16c0-8.84-7.16-16-16-16H176c-8.84 0-16 7.16-16 16v16zm96 121.13c-16.42 0-32.84-5.06-46.86-15.19L0 250.86V464c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V250.86L302.86 401.94c-14.02 10.12-30.44 15.19-46.86 15.19zm237.61-254.18c-8.85-6.94-17.24-13.47-29.61-22.81V96c0-26.51-21.49-48-48-48h-77.55c-3.04-2.2-5.87-4.26-9.04-6.56C312.6 29.17 279.2-.35 256 0c-23.2-.35-56.59 29.17-73.41 41.44-3.17 2.3-6 4.36-9.04 6.56H96c-26.51 0-48 21.49-48 48v44.14c-12.37 9.33-20.76 15.87-29.61 22.81A47.995 47.995 0 0 0 0 200.72v10.65l96 69.35V96h320v184.72l96-69.35v-10.65c0-14.74-6.78-28.67-18.39-37.77z" />
              </svg>
            </span>
            <div className="text-left ml-2.5">
              <p className="text-xs text-[#A6A6A6]">
                Email
              </p>
              <p className="text-white break-all">
                <a
                  className="hover:text-primary duration-300 transition"
                  href="mailto:ibthemes21@gmail.com"
                >
                  example@mail.com
                </a>
              </p>
            </div>
          </div>
          <div className="flex py-2.5 undefined">
            <span className="flex-shrink-0 socialbtn bg-black text-[#C17CEB] shadow-md">
              <svg
                stroke="currentColor"
                fill="currentColor"
                strokeWidth={0}
                viewBox="0 0 448 512"
                height="1em"
                width="1em"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M0 464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V192H0v272zm320-196c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM192 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12h-40c-6.6 0-12-5.4-12-12v-40zM64 268c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zm0 128c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H76c-6.6 0-12-5.4-12-12v-40zM400 64h-48V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H160V16c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v48H48C21.5 64 0 85.5 0 112v48h448v-48c0-26.5-21.5-48-48-48z" />
              </svg>
            </span>
            <div className="text-left ml-2.5">
              <p className="text-xs text-[#A6A6A6]">
                Birthday
              </p>
              <p className="text-white break-all">May 27, 1990</p>
            </div>
          </div>
        </div>
        <a
          href="/images/cv.pdf"
          download=""
          className="inline-flex items-center mx-auto bg-gradient-to-r from-primary to-secondary duration-200 transition ease-linear hover:bg-gradient-to-l px-8 py-3 text-lg text-white rounded-[35px] mt-6"
        >
         Download CV
        </a>
          
      </div>
    </div>
    
  </div>
  <div className="col-span-12 lg:col-span-8">
    <MainNavbar />
   
    {children}
    <footer className="overflow-hidden rounded-b-2xl bg-black">
        <div className="container">
          <p className="text-center py-6 text-white">
            © 2023 All Rights Reserved by
            <a className="hover:text-[#FA5252] duration-300 transition" href="https://themeforest.net/user/ib-themes" target="_blank" rel="noopener noreferrer">ib-themes</a>.
          </p>
        </div>
      </footer>
  </div>
</div>
        
        </section>
 
        </body>
    </html>
  )
}
